### ISSUE TITLE
JSONDecodeError in requests module (python3.11\3.9)

### ISSUE THREAD

**Issue by Marcelas751** [alxrem/certbot-dns-selectel-api-v2#1]
Waiting 30 seconds for DNS changes to propagate
Encountered exception during recovery: AttributeError: module 'requests' has no attribute 'JSONDecodeError'
Пробовал с разными версиями питона на Ubuntu 22.04 Server. Судя по всему возвращается ответ от Селектела который он пытается распарсить но не может из-за ошибки. Такая же история при заказе wildcard

**Comment by Marcelas751** [comment]
```
    def _api(self, method, uri, data=None, params=None):
        resp = self._r(method, uri,
                       headers={"X-Auth-Token": self._token},
                       params=params,
                       json=data)
        return resp.content
```
так работает

**Comment by alxrem** [comment]
Выпустил 0.2.0, должно помочь.

**Comment by Marcelas751** [comment]
увы)
An unexpected error occurred:
TypeError: byte indices must be integers or slices, not str

**Comment by Marcelas751** [comment]
2024-08-23 15:04:49,939:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-08-23 15:04:49,940:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-08-23 15:04:49,941:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/main.py", line 1894, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.11/dist-packages/certbot_dns_selectel_api_v2-0.1.0-py3.11.egg/certbot_dns_selectel_api_v2/dns_selectel_api_v2.py", line 63, in _perform
    self._client.update_record(
  File "/usr/local/lib/python3.11/dist-packages/certbot_dns_selectel_api_v2-0.1.0-py3.11.egg/certbot_dns_selectel_api_v2/dns_selectel_api_v2.py", line 197, in update_record
    resp = self._api(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot_dns_selectel_api_v2-0.1.0-py3.11.egg/certbot_dns_selectel_api_v2/dns_selectel_api_v2.py", line 121, in _api
    resp = self._r(method, uri,
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot_dns_selectel_api_v2-0.1.0-py3.11.egg/certbot_dns_selectel_api_v2/dns_selectel_api_v2.py", line 114, in _r
    message_parts.append(answer["error"])
                         ~~~~~~^^^^^^^^^

**Comment by Marcelas751** [comment]
[letsencrypt.log](https://github.com/user-attachments/files/16728729/letsencrypt.log)
то что выше через setup.py install
установка через pip3.11 install -e /opt/certbot-dns-selectel-api-v2-0.2.0 дает:
API request error: status code 422, bad_request
Думаю стоит уточнить в readme метод установки

**Comment by Marcelas751** [comment]
то что выше через setup.py install

**Comment by Marcelas751** [comment]
Наше причину, 422 появляется при уже имеющейся группе записей _acme-challenge и значениями в ней

**Comment by alxrem** [comment]
Да, вроде, я это обрабатывал. Попробую воспроизвести.

**Comment by Marcelas751** [comment]
Есть еще вот такой прикол в 182 строке отрабатывает:
        raise errors.PluginError(f"Zone not found for domain {domain}")
но зона на месте, просто заказываю на 4 уровень wildcard:

root@gate:/home/devops# certbot -v certonly -a dns-selectel-api-v2 --dns-selectel-api-v2-credentials /root/.selectel/cred.ini --dns-selectel-api-v2-propagation-seconds 30 -d *.eftech.online -d eftech.online -d *.3dgenerator.eftech.online -d *.agb.eftech.online -d *.alur.eftech.online -d *.approval.eftech.online -d *.base.eftech.online -d *.booking.eftech.online -d *.checklists.eftech.online -d *.demo.approval.eftech.online -d *.demo.base.eftech.online -d *.demo.factory.eftech.online -d *.factory.eftech.online -d *.im.eftech.online -d *.kazan-expo.eftech.online -d *.kolpack.eftech.online -d *.most.eftech.online -d *.nipom.eftech.online -d *.proq.eftech.online -d *.release.factory.eftech.online -d *.rest.eftech.online -m admin@eftech.online --agree-tos -n
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-selectel-api-v2, Installer None
Requesting a certificate for *.eftech.online and 20 more domains
Performing the following challenges:
dns-01 challenge for 3dgenerator.eftech.online
dns-01 challenge for agb.eftech.online
dns-01 challenge for alur.eftech.online
dns-01 challenge for approval.eftech.online
dns-01 challenge for base.eftech.online
dns-01 challenge for booking.eftech.online
dns-01 challenge for checklists.eftech.online
dns-01 challenge for demo.approval.eftech.online
dns-01 challenge for demo.base.eftech.online
dns-01 challenge for demo.factory.eftech.online
dns-01 challenge for eftech.online
dns-01 challenge for factory.eftech.online
dns-01 challenge for im.eftech.online
dns-01 challenge for kazan-expo.eftech.online
dns-01 challenge for kolpack.eftech.online
dns-01 challenge for most.eftech.online
dns-01 challenge for nipom.eftech.online
dns-01 challenge for proq.eftech.online
dns-01 challenge for release.factory.eftech.online
dns-01 challenge for rest.eftech.online
dns-01 challenge for eftech.online
Cleaning up challenges
Zone not found for domain 3dgenerator.eftech.online

Вот что предлагает старый плагин
https://github.com/Shm013/certbot-dns-selectel/blob/a8a0d25b54e3341d4b230c60faaecb6d35517722/certbot_dns_selectel/dns_selectel.py#L108

**Comment by Marcelas751** [comment]
@alxrem оставил pull request с фиксом

**Comment by alxrem** [comment]
Нужно вытащить отдельные баги на zone not found и на 422. Это всё разные проблемы.

Вечером освобожусь, растащу. Или сам.

PR надо будет привязать к баге про зону, закрыть комментарий, и можно будет релизить.

**Comment by alxrem** [comment]
Тут исходная ошибка исправлена, остальные разнесены по своим тикетам. Закрываем.
