### ISSUE TITLE
Ошибка на домене 4 уровня

### ISSUE THREAD

**Issue by alxrem** [alxrem/certbot-dns-selectel-api-v2#4]
Есть еще вот такой прикол в 182 строке отрабатывает:
        raise errors.PluginError(f"Zone not found for domain {domain}")
но зона на месте, просто заказываю на 4 уровень wildcard:

root@gate:/home/devops# certbot -v certonly -a dns-selectel-api-v2 --dns-selectel-api-v2-credentials /root/.selectel/cred.ini --dns-selectel-api-v2-propagation-seconds 30 -d *.eftech.online -d eftech.online -d *.3dgenerator.eftech.online -d *.agb.eftech.online -d *.alur.eftech.online -d *.approval.eftech.online -d *.base.eftech.online -d *.booking.eftech.online -d *.checklists.eftech.online -d *.demo.approval.eftech.online -d *.demo.base.eftech.online -d *.demo.factory.eftech.online -d *.factory.eftech.online -d *.im.eftech.online -d *.kazan-expo.eftech.online -d *.kolpack.eftech.online -d *.most.eftech.online -d *.nipom.eftech.online -d *.proq.eftech.online -d *.release.factory.eftech.online -d *.rest.eftech.online -m admin@eftech.online --agree-tos -n
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-selectel-api-v2, Installer None
Requesting a certificate for *.eftech.online and 20 more domains
Performing the following challenges:
dns-01 challenge for 3dgenerator.eftech.online
dns-01 challenge for agb.eftech.online
dns-01 challenge for alur.eftech.online
dns-01 challenge for approval.eftech.online
dns-01 challenge for base.eftech.online
dns-01 challenge for booking.eftech.online
dns-01 challenge for checklists.eftech.online
dns-01 challenge for demo.approval.eftech.online
dns-01 challenge for demo.base.eftech.online
dns-01 challenge for demo.factory.eftech.online
dns-01 challenge for eftech.online
dns-01 challenge for factory.eftech.online
dns-01 challenge for im.eftech.online
dns-01 challenge for kazan-expo.eftech.online
dns-01 challenge for kolpack.eftech.online
dns-01 challenge for most.eftech.online
dns-01 challenge for nipom.eftech.online
dns-01 challenge for proq.eftech.online
dns-01 challenge for release.factory.eftech.online
dns-01 challenge for rest.eftech.online
dns-01 challenge for eftech.online
Cleaning up challenges
Zone not found for domain 3dgenerator.eftech.online

Вот что предлагает старый плагин
https://github.com/Shm013/certbot-dns-selectel/blob/a8a0d25b54e3341d4b230c60faaecb6d35517722/certbot_dns_selectel/dns_selectel.py#L108

_Originally posted by @Marcelas751 in https://github.com/alxrem/certbot-dns-selectel-api-v2/issues/1#issuecomment-2309585673_

**Comment by Marcelas751** [comment]
@alxrem связал с issue
